name: Build

on:
  push:
    branches: [astria]
  pull_request:
    branches: [astria]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Generate
        run: go generate -x

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v ./...

  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: yarn install
        working-directory: web

      - run: yarn prettier --check 'src/**/*.{css,html,js,svelte}'
        working-directory: web
